//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee170220.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Office { get; set; }
        public string Position { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<bool> IsCurrentEmployee { get; set; }
        public string ImagePath { get; set; }
    }
}
