<?xml version="1.0" encoding="utf-8"?><Database Name="HomeDatabase" Class="EmployeeInfo2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=BRINTA-PC;Initial Catalog=HomeDatabase;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HomeDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmployeeInfo2" Member="EmployeeInfo2s">
    <Type Name="EmployeeInfo2">
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Salary" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>