//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeHBJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo5
    {
        public int EmpId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<double> SalaryPerDay { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
