//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentHtmlTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string First_Name { get; set; }
        [Required(ErrorMessage = "Name Required!")]
        public string Last_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        [DisplayName("Profile")]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
        public Employee()
        {
            ImagePath = "~/AppFiles/ImageFiles/Default.png";
        }
    }
}
