//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCRUDAjax.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Employee
    {
        public int EmployeeId { get; set; }
        
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last Name Required!")]
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
        public Nullable<double> CurrentSalary { get; set; }
        public Nullable<double> LastRevisedSalary { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<bool> IsCurrentEmployee { get; set; }
        public Nullable<System.DateTime> LastSalaryIncrementDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ImagePath { get; set; }
    }
}
